name: 'Just testing typescript action'
description: 'Provide a description here'
author: 'liblaber'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

inputs:
  liblab_token:
    description: 'The Liblab authentication token provided by liblab CLI'
    required: true
  github_token:
    description: 'The github token that will allow posting PRs to SDK repos'
    required: true

outputs:
  status:
    description: 'Status of the build'

runs:
  using: node20
  main: dist/index.js
